### ISSUE TITLE
Abstracting code

### ISSUE THREAD

**Issue by zannain** [quixotep/prj-rev-bwfs-dasmoto#1]
Great work on creating descriptive class names like `.mediumspringgreen` and `.lightcoral`. This practice of abstracting common code into a CSS class will serve you well as you start working on large codebases. I would suggest though abstracting should be one of last things you do because once you have written a good amount of code you will begin to noticed common patterns repeat and these are flags that you can refactor somewhere. For example, a lot of your classes have some common code you could [abstract](https://github.com/quixotep/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Web%20Design/resources/style.css#L9-L35).

```css
.default-styles {
     font-weight: bold;
     font-family: Helvetica;
}
```
